name: 1 - Hello World
on: [push] 
jobs:
  hello_world:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - name: Print a greeting
      run : echo "Hello"
    # - uses: actions/first-interaction@v1
    #   with:
    #     repo-token: ${{ secrets.GITHUB_TOKEN }}
    #     issue-message: "Message that will be displayed on users' first issue"
    #     pr-message: "Message that will be displayed on users' first pull request"
